# Generated by Django 3.2.1 on 2021-06-25 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Brend nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Categoriyalar nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('content', models.CharField(max_length=150, verbose_name='Malumoti')),
                ('sales', models.BooleanField(blank=True, choices=[(True, 'BOR'), (False, 'YOQ')], null=True, verbose_name='Sotuvda')),
                ('repair_service', models.CharField(blank=True, max_length=200, verbose_name='Servis xizmat')),
                ('warranty', models.CharField(blank=True, max_length=200, verbose_name='Kafolat mudati')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('additional_data', models.TextField(verbose_name="Qo'shimacha malumotlari")),
                ('images', models.ImageField(upload_to=main_shop.models.brand_image, verbose_name='Rasm')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_category', models.CharField(max_length=150, verbose_name='Categorya nomi')),
                ('card_brand', models.CharField(max_length=150, verbose_name='Bend nomi')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('images', models.CharField(max_length=1000, verbose_name='Rasm')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
