# Generated by Django 3.2.1 on 2021-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('tuman', models.CharField(max_length=100, verbose_name='Tuman')),
                ('mahalla', models.TextField(verbose_name="Mahalla va qishloq nomi ko'cha nomi ")),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism Familya')),
                ('uy_raqami', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='Maxsulot rangi'),
            preserve_default=False,
        ),
    ]
