# Generated by Django 3.2.1 on 2021-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0002_auto_20210628_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
        migrations.AddField(
            model_name='card',
            name='content',
            field=models.CharField(default=1, max_length=150, verbose_name='Malumoti'),
            preserve_default=False,
        ),
    ]
