# Generated by Django 3.2.1 on 2021-06-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0004_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='carts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_shop.card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='mahalla',
            field=models.CharField(max_length=250, verbose_name="Mahalla va qishloq nomi ko'cha nomi "),
        ),
    ]
