# Generated by Django 3.2.1 on 2021-06-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0005_auto_20210629_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='carts',
            new_name='ca',
        ),
    ]
