# Generated by Django 3.2.1 on 2021-06-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_shop', '0006_rename_carts_adress_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='ca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='main_shop.card'),
        ),
    ]
